---
- name: Socks tunnel setup
  hosts: all
  gather_facts: no
  roles:
  - role: ansible-role-event-socks-tunnel
    run_once: true
    delegate_to: localhost
    vars:
      acc_id: "{{ account_triname }}"
      transaction_id: "{{ tower_job_id }}"

- name: Check FTP Service
  hosts: all
  gather_facts: yes

  tasks: 

  - name: Powershell run 1
    win_shell: |
          Get-Service "Microsoft FTP Service" -ErrorAction SilentlyContinue
    register: eventinfo1
    failed_when: "eventinfo1.rc not in [ 0, 1 ]"

  - name: Powershell run 2
    win_shell: |
          Get-Service "FTP Publishing Service" -ErrorAction SilentlyContinue
    register: eventinfo2
    failed_when: "eventinfo2.rc not in [ 0, 1 ]" 
    
#  - name: show events
#    debug:
#      msg: "Server: {{ ansible_hostname }} - {{ eventinfo.stdout_lines }}"

  - name: set bool var
    set_fact:
      b_var: "{% for res in eventinfo1.stdout_lines %}
              {% if 'Microsoft FTP Service' in res %}
	      1
              {% else %}
              0
              {% endif %}
              {% endfor %}"
              
  - name: set bool var
    set_fact:
      a_var: "{% for res in eventinfo2.stdout_lines %}
               {% if 'FTP Publishing Service' in res %}
	       1
               {% else %}
               0
               {% endif %}
               {% endfor %}"

 # - name: b_var output
 #   debug:
 #     var: b_var
    
  - name: filter events & give result 'found' or 'not found'
    set_fact:
      out_var: "{% if '1' in b_var or '1' in a_var %}
            found 
            {% else %}
            not found
            {% endif %}"

#  - name: output list
#    debug:
#      msg: "{{ out_var }}"

  - name: passagem de variáveis para output
    set_stats:
      data:
        file_content: "{{ ansible_hostname }} - {{ out_var }}\n"
      aggregate: yes
      per_host: no
...
